### ISSUE TITLE
Cache invalidation using serverless framework

### ISSUE THREAD

**Issue by hakimio** [MadSkills-io/fullstack-serverless#10]
Could you add CloudFront cache invalidation to this plugin like it's done in `serverless-single-page-app-plugin`: [invalidation function](https://github.com/erezrokah/serverless-monorepo-app/blob/5e52ac580bd76970d5eb598cfcf24228a1912821/frontend/serverless-single-page-app-plugin/index.js#L89)?

**Comment by andrewphahn** [comment]
Cache invalidation is one of the things I have wanted to add since the beginning. Thanks for a pointer to a way to do it. By all means, please submit a pull request!

I run invalidation with npm as a workaround
# package.json
```json
...
  "scripts": {
    "invalidate:dev": "aws cloudfront create-invalidation --distribution-id <dist id> --paths '/*' --profile <profile>",
    "invalidate:prod": "aws cloudfront create-invalidation --distribution-id <dist id> --paths '/*' --profile <profile>"
  }
...
```

Then run

```bash
npm run invalidate:dev
```

**Comment by hakimio** [comment]
Thanks for the tip on how to do it with aws cli. 
I'll see if I can put together a PR to add cache invalidation to this project next week.

**Comment by hakimio** [comment]
@andrewphahn See PR #13
