### ISSUE TITLE
Using shared API Gateway

### ISSUE THREAD

**Issue by hakimio** [MadSkills-io/fullstack-serverless#11]
According to [serverless documentation](https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources) shared API Gateway can be used by defining `restApiId` and `restApiRootResourceId` configs in provider section. It seems this plugin disregards those configs and just tries to find API Gateway definition in resources section. 
@andrewphahn Could you make the change to enable shared gateway usage?

**Comment by andrewphahn** [comment]
Oh interesting, I'll take a look.

**Comment by hakimio** [comment]
@andrewphahn Check PR #12
