### ISSUE TITLE
Option to deploy functions only

### ISSUE THREAD

**Issue by andyautida14** [MadSkills-io/fullstack-serverless#32]
Hello!

I like this library a lot. But I'm currently just using my mobile data to deploy some pet project to AWS.

Sometimes I have to deploy all the functions because for some reason, some files I `require()` from the function handler doesn't get updated if I upload only the specific function I have changes on. Deploying the whole project including the front-end stuff eats a considerable chunk of my data package.

Is there an option to deploy only all the functions, skipping the front-end, that I'm not aware of? If not, I think it's a great feature to have.

Thanks!

**Comment by andrewphahn** [comment]
There is a flag, and I just realized it is not in the docs. I believe it is
—no-client-deploy, I’ll verify later today.

**Comment by andyautida14** [comment]
That's helpful. Thank you!

**Comment by andrewphahn** [comment]
Added `--no-client-deploy` flag in 0.8.0
