### ISSUE TITLE
Deploying without API Gateway passthrough

### ISSUE THREAD

**Issue by TomFrost** [MadSkills-io/fullstack-serverless#34]
I'd love to use fullstack-serverless to deploy my autogenerated html API docs. This seems to be the best supported (and potentially only) serverless plugin that handles s3 buckets and cloudfront distributions end-to-end.

However, there appears to be a deep tie-in to API Gateway that this use case doesn't require. I'm only pushing static web files to a separate domain than my API domain.

Would you recommend fullstack-serverless for this use case, and do you have any configuration recommendations to eliminate unnecessary infrastructure being created?

Thanks so much -- this library looks spectacular!

**Comment by andrewphahn** [comment]
I use fullstack-serverless to deploy static sites without any API Gateway resources for a couple projects. It only deploys an API Gateway origin/endpoints if you define functions in `serverless.yml`.

Closing as it already does what you are asking about. Feel free to reopen if I got it wrong 😀

**Comment by TomFrost** [comment]
Lovely -- so sorry I didn't catch that! This is really fantastic. Thank you! :)
